### ISSUE TITLE
Deprecate ome/omero-py package in favor of conda-forge

### ISSUE THREAD

**Issue by sbesson** [ome/conda-omero-py#26]
Thanks to the work on https://github.com/conda-forge/staged-recipes/pull/17721, `omero-py` is now available as a package from `conda-forge` - see https://libraries.io/conda/omero-py

From a quick testing including the recent work from @manics on the `zeroc-ice` 3.6 backport in an `arm64` environment, it is possible to spin up a functional OMERO.py environment using `conda install -c conda-forge omero-py ` and/or a simple environment file

```yml
---
name: omero_py
channels:
  - conda-forge
dependencies:
  - omero-py
```

Additionally, the `conda-forge` ecosystem  benefits from auto-bump automated infrastructure similar to what @jburel put in place in https://github.com/ome/conda-omero-py/commit/c3ae0af5d1dd184aacdf89055aa0fef83c21b2d4 - see  https://github.com/conda-forge/omero-py-feedstock/pull/1 for an example and the automated bump to the latest OMERO.py release.

All the above probably makes this repository and the associated package on the `ome` channel largely redundant. I would propose to do the following:

- edit the description of https://anaconda.org/ome/omero-py to mark it as deprecated and redirect explictly to `conda-forge`
- update the README of this repository to have similar information
- archive this GitHub repository
- review the various places using the `ome` channel, primarily guides and omero-documentation to use the new `conda-forge` workflow
- if space becomes an issue, start deleting older packages on the `ome` Conda channel

Possibly the order could be inverted and we could start by the last item to test the `conda-forge` package meets our requirements /cc @pwalczysko

**Comment by jburel** [comment]
The various binder environments will need to be updated.

**Comment by sbesson** [comment]
> The various binder environments will need to be updated.

Would you say they need to be updated before we deprecate this package?

**Comment by jburel** [comment]
Ideally yes if we want to install the latest version of omero-py.
I am looking into it

**Comment by jburel** [comment]
All repositories using the ``ome`` channel have now been updated

**Comment by joshmoore** [comment]
Ah, one issue left. Shall I hold off for this checklist for archiving the repo, @sbesson ?

**Comment by sbesson** [comment]
Thanks for reminding me. Pushed a commit. Let's archive this (and probably do the same on https://github.com/ome/conda-zeroc-ice36-python)
